server:
  port: 8989
spring:
  application:
    name: JavaRun
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/short_url?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  mvc:
    static-path-pattern: static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rawchen.shorturl.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    #控制台打印mapper接口的sql语句日志
    com.rawchen.shorturl.mapper: debug